CREATE TABLE Transactions(
    date Date,
    timestamp DateTime,
    transaction_hash String,
    from_address String,
    to_address String,
    value UInt64,
    type_tx String,
    block_number UInt64,
    signature_hash String,
    fee UInt64,
    fee_real UInt64,
    nonce UInt64,
    status String,
    status_int UInt64,
    is_delegate UInt8,
    delegate_info String,
    delegate UInt64,
    delegate_hash String,
    data_raw String,
    data_string String,
    method String
) ENGINE = ReplacingMergeTree() ORDER BY (date, timestamp, transaction_hash, from_address) PRIMARY KEY (date, timestamp, transaction_hash)
